/** Semua teks yang tampil ke pemain. */
import type { KodeGalatPeringkat } from '../app/peringkat';
import type { EventId, FasilitasId, KelasBusId, PencapaianId, PoId, TeknologiId } from '../sim/fitur';
import type { TahapId } from '../sim/tahap';
import type { TingkatKeramaian } from '../sim/waktu';

export const NAMA_TAHAP: Readonly<Record<TahapId, string>> = {
  peron: 'Peron',
  loket: 'Loket',
  keberangkatan: 'Keberangkatan',
};

/** Nama hari, indeks 0 = Senin (lihat sim/waktu.ts). */
export const NAMA_HARI: readonly string[] = ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu', 'Minggu'];

export const NAMA_FASILITAS: Readonly<Record<FasilitasId, { readonly nama: string; readonly deskripsi: string }>> = {
  kios: { nama: 'Kios & Minimarket', deskripsi: 'Sewa dibayar tiap hari, dari belanja penumpang' },
  parkir: { nama: 'Parkir Kendaraan', deskripsi: 'Parkir kendaraan pengantar & penjemput' },
  toilet: { nama: 'Toilet & Musholla', deskripsi: 'Penumpang betah, belanja di kios naik' },
  retribusi: { nama: 'Parkir Bus Jurusan', deskripsi: 'Dibayar tiap bus yang parkir di pulau jurusannya' },
};

/** Mitra PO (semua nama fiktif) dan kota asalnya. */
export const NAMA_PO: Readonly<Record<PoId, { readonly nama: string; readonly asal: string }>> = {
  lumpiaKilat: { nama: 'PO Lumpia Kilat', asal: 'Semarang' },
  bakpiaRasa: { nama: 'PO Bakpia Rasa', asal: 'Yogyakarta' },
  wayangLestari: { nama: 'PO Wayang Lestari', asal: 'Solo' },
  arekEkspres: { nama: 'PO Arek Ekspres', asal: 'Surabaya' },
  apelBatu: { nama: 'PO Apel Batu', asal: 'Malang' },
  kecakLaju: { nama: 'PO Kecak Laju', asal: 'Denpasar' },
  sigerSakti: { nama: 'PO Siger Sakti', asal: 'Lampung' },
  rinjaniIndah: { nama: 'PO Rinjani Indah', asal: 'Mataram' },
  rumahGadang: { nama: 'PO Rumah Gadang', asal: 'Padang' },
  danauToba: { nama: 'PO Danau Toba', asal: 'Medan' },
  kopiGayo: { nama: 'PO Kopi Gayo', asal: 'Banda Aceh' },
  ondelOndel: { nama: 'PO Ondel-Ondel', asal: 'Jakarta' },
  peuyeumKilat: { nama: 'PO Peuyeum Kilat', asal: 'Bandung' },
  teloletJaya: { nama: 'PO Telolet Jaya', asal: 'Jepara' },
  sultanGarasi: { nama: 'PO Sultan Garasi', asal: 'Jakarta' },
  juaraKelas: { nama: 'PO Juara Kelas', asal: 'Bogor' },
  juaraUmum: { nama: 'PO Juara Umum', asal: 'Medan' },
  mudikCeria: { nama: 'PO Mudik Ceria', asal: 'Cirebon' },
  merahPutih: { nama: 'PO Merah Putih', asal: 'Jakarta' },
  kembangApi: { nama: 'PO Kembang Api', asal: 'Makassar' },
};

/** Event musiman: nama lengkap, nama singkat (HUD), dan ikon notifikasi. */
export const NAMA_EVENT: Readonly<Record<EventId, { readonly nama: string; readonly singkat: string; readonly ikon: string }>> = {
  mudikLebaran: { nama: 'Mudik Lebaran', singkat: 'Mudik', ikon: '🌙' },
  hutRi: { nama: 'HUT Kemerdekaan RI', singkat: 'HUT RI', ikon: '🎉' },
  nataru: { nama: 'Libur Natal & Tahun Baru', singkat: 'Nataru', ikon: '🎆' },
};

/** Sisa waktu event: "5 hari", "7 jam", "12 menit". */
export function sisaWaktuEvent(ms: number): string {
  const menit = Math.max(1, Math.floor(ms / 60_000));
  if (menit >= 1440) return `${Math.floor(menit / 1440)} hari`;
  if (menit >= 60) return `${Math.floor(menit / 60)} jam`;
  return `${menit} menit`;
}

const BULAN_SINGKAT: readonly string[] = ['Jan', 'Feb', 'Mar', 'Apr', 'Mei', 'Jun', 'Jul', 'Agu', 'Sep', 'Okt', 'Nov', 'Des'];

/** Rentang minggu Senin–Minggu dari kuncinya ("2026-09-21" → "21–27 Sep", lintas bulan "29 Des – 4 Jan"). */
export function rentangMinggu(kunci: string): string {
  const [t, b, h] = kunci.split('-').map(Number) as [number, number, number];
  const awal = new Date(Date.UTC(t, b - 1, h));
  const akhir = new Date(Date.UTC(t, b - 1, h + 6));
  const bAwal = BULAN_SINGKAT[awal.getUTCMonth()]!;
  const bAkhir = BULAN_SINGKAT[akhir.getUTCMonth()]!;
  return bAwal === bAkhir ? `${awal.getUTCDate()}–${akhir.getUTCDate()} ${bAkhir}` : `${awal.getUTCDate()} ${bAwal} – ${akhir.getUTCDate()} ${bAkhir}`;
}

/** Pesan galat papan peringkat untuk pemain (lihat KODE_GALAT_PERINGKAT). */
export const GALAT_PERINGKAT: Readonly<Record<KodeGalatPeringkat, string>> = {
  token: 'Sesi login berakhir. Masuk lagi lewat menu akun supaya skormu terkirim.',
  dilarang: 'Akun ini diblokir dari papan peringkat.',
  'terlalu-sering': 'Skor belum terkirim. Dicoba lagi otomatis.',
  'minggu-lain': 'Tanggal & jam perangkatmu tidak sesuai, jadi skor tidak bisa dikirim. Periksa pengaturan jam.',
  'nama-kosong': 'Beri nama terminalmu dulu supaya tampil di papan.',
  'nama-ditolak': 'Nama terminalmu tidak bisa tampil di papan. Ganti namanya dulu.',
  'skor-tidak-wajar': 'Skormu ditolak server karena naik terlalu cepat.',
  'data-salah': 'Skor belum terkirim. Perbarui game ke versi terbaru.',
  server: 'Papan peringkat sedang gangguan. Skor dicoba kirim lagi otomatis.',
  jaringan: 'Tidak ada koneksi. Skor dicoba kirim lagi otomatis.',
};

/** Nama kelas terminal: 0 = Tipe C, 1 = Tipe B, 2 = Tipe A, lalu Terpadu dengan bintang. */
export function namaKelas(kelas: number): string {
  if (kelas <= 0) return 'Tipe C';
  if (kelas === 1) return 'Tipe B';
  if (kelas === 2) return 'Tipe A';
  return `Terpadu ★${kelas - 2}`;
}

export const NAMA_TEKNOLOGI: Readonly<Record<TeknologiId, string>> = {
  rambuHalte: 'Marka & rambu halte',
  pengaturBus: 'Petugas pengatur bus',
  mesinTiket: 'Mesin tiket mandiri',
  eTiket: 'Tiket online (e-tiket)',
  jadwalDigital: 'Papan jadwal digital',
  gateOtomatis: 'Gate e-boarding otomatis',
};

/** Kelas bus armada terminal (tab Armada). */
export const NAMA_KELAS_BUS: Readonly<Record<KelasBusId, { readonly nama: string; readonly deskripsi: string }>> = {
  ekonomi: { nama: 'Ekonomi', deskripsi: 'Bus kota tanpa AC, tarif paling murah' },
  patas: { nama: 'Patas AC', deskripsi: 'Cepat terbatas berpendingin udara' },
  eksekutif: { nama: 'Eksekutif', deskripsi: 'High deck, kursi lega, kaca gelap' },
  sleeper: { nama: 'Sleeper', deskripsi: 'Kabin tidur untuk perjalanan malam' },
  tingkat: { nama: 'Double Decker', deskripsi: 'Bus tingkat dua dek' },
};

export const NAMA_PENCAPAIAN: Readonly<Record<PencapaianId, { readonly nama: string; readonly deskripsi: string }>> = {
  kepalaPertama: { nama: 'Manajemen Profesional', deskripsi: 'Rekrut Kepala pertama' },
  fasilitasPertama: { nama: 'Terminal Nyaman', deskripsi: 'Bangun fasilitas pertama' },
  semuaOtomatis: { nama: 'Berjalan Sendiri', deskripsi: 'Ketiga tahap punya Kepala' },
  targetPertama: { nama: 'Tepat Sasaran', deskripsi: 'Selesaikan target harian' },
  level25: { nama: 'Terminal Megah', deskripsi: 'Semua tahap Lv 25' },
  penumpang100rb: { nama: 'Seratus Ribu Perjalanan', deskripsi: 'Berangkatkan 100.000 penumpang' },
  sepekan: { nama: 'Sepekan Beroperasi', deskripsi: 'Beroperasi 7 hari terminal' },
  fasilitasLengkap: { nama: 'Fasilitas Lengkap', deskripsi: 'Semua fasilitas Lv 10' },
  jalurLengkap: { nama: 'Lima Jalur', deskripsi: 'Semua jalur bus beroperasi' },
  jurusanSemua: { nama: 'Penghubung Jawa–Bali', deskripsi: 'Buka semua jurusan Jawa–Bali' },
  antarpulau: { nama: 'Menyeberang Pulau', deskripsi: 'Buka rute antarpulau pertama' },
  kelasB: { nama: 'Naik Kelas', deskripsi: 'Terminal naik ke Tipe B' },
  modernLengkap: { nama: 'Terminal Modern', deskripsi: 'Pasang semua modernisasi' },
  level100: { nama: 'Terminal Raksasa', deskripsi: 'Semua tahap Lv 100' },
  kelasA: { nama: 'Terminal Tipe A', deskripsi: 'Terminal naik ke Tipe A' },
  armadaLengkap: { nama: 'Armada Lengkap', deskripsi: 'Semua kelas bus beroperasi, sampai Double Decker' },
  penumpang10jt: { nama: 'Sepuluh Juta Perjalanan', deskripsi: 'Berangkatkan 10 juta penumpang' },
  lintasNusantara: { nama: 'Lintas Nusantara', deskripsi: 'Buka semua rute sampai Banda Aceh' },
};

/** Label keramaian di bawah jam HUD. */
export const LABEL_KERAMAIAN: Readonly<Record<TingkatKeramaian, string>> = {
  sibuk: 'Jam sibuk',
  ramai: 'Ramai',
  sedang: 'Sedang',
  sepi: 'Sepi',
};

export const TEKS = {
  siang: 'Siang',
  malam: 'Malam',
  hujan: 'Hujan',
  judul: 'Bustation: Idle Bus',
  level: (n: number) => `Lv ${n}`,
  satuanArus: 'pnp/dtk',
  hudHariIni: (rp: string, tiket: string) => `Hari ini ${rp} · ${tiket} tiket`,
  hudHariIniRingkas: (rp: string) => `Hari ini ${rp}`,
  arus: 'Arus',
  upgrade: 'Upgrade',
  rekrutKepala: 'Rekrut Kepala',
  adaKepala: 'Ada Kepala',
  palingLambat: 'PALING LAMBAT',
  milestoneMenuju: (level: number, pengali: number) => `Lv ${level}: kapasitas ×${pengali}`,
  milestoneSelesai: 'Semua milestone tercapai',
  petunjukKepala: 'Rekrut Kepala di ketiga tahap supaya terminal tetap jalan saat kamu pergi.',
  // Tutorial terpandu (ui/tutorial.ts).
  tutorialSambutanJudul: 'Selamat datang, Kepala Terminal!',
  tutorialSambutan:
    'Penumpang turun di Peron, membeli tiket di Loket, lalu naik bus di Keberangkatan. Tahap yang paling lambat menentukan pendapatanmu.',
  tutorialMulai: 'Mulai',
  tutorialLewati: 'Lewati',
  tutorialOke: 'Oke',
  tutorialNomor: (ke: number, dari: number) => `Langkah ${ke}/${dari}`,
  tutorialUpgradeJudul: 'Percepat tahap paling lambat',
  tutorialUpgrade: (tahap: string) => `Terminalmu sudah berjalan dan uang masuk sendiri. Upgrade ${tahap} (bertanda PALING LAMBAT) supaya lebih banyak penumpang terlayani.`,
  tutorialKepalaJudul: 'Rekrut Kepala',
  tutorialKepala: (tahap: string) => `Rekrut Kepala ${tahap}. Dengan Kepala di ketiga tahap, terminal tetap berjalan saat game ditutup.`,
  tutorialFasilitasJudul: 'Bangun fasilitas',
  tutorialFasilitas: 'Buka tab Fasilitas, lalu bangun Kios & Minimarket: penumpang berbelanja dan sewanya dibayar tiap hari.',
  tutorialJalurJudul: 'Bangun Jalur 2',
  tutorialJalur: 'Terminalmu baru punya satu jalur, jadi bus mengantre di jalan raya. Di tab Fasilitas, bangun Jalur 2: Peron & Keberangkatan jadi lebih cepat.',
  tutorialUang: (uang: string, biaya: string) => `Uang ${uang} / ${biaya}`,
  tutorialUangCukup: 'Uang cukup! Ketuk tombol yang berkedip.',
  // Tantangan mingguan & rekor (tab Target).
  tantanganJudul: (sisa: string) => `🎯 Tantangan minggu ini · berakhir dalam ${sisa}`,
  tantanganBerakhir: '🎯 Tantangan minggu ini · sudah berakhir',
  tantanganPenumpang: (n: string) => `Berangkatkan ${n} penumpang`,
  tantanganPendapatan: (rp: string) => `Kumpulkan ${rp} dari operasi terminal`,
  tantanganUpgrade: (n: number) => `Lakukan ${n} upgrade tahap`,
  tantanganKepuasan: (persen: number, menit: number) => `Jaga kepuasan ≥ ${persen}% selama ${menit} menit main`,
  tantanganFasilitas: (n: number) => `Naikkan level fasilitas ${n} kali`,
  tantanganMenit: (ada: number, target: number) => `${ada} / ${target} menit`,
  tantanganCatatan: 'Tantangan baru tiap Senin (WIB). Hadiah yang lupa diklaim dikirim otomatis minggu berikutnya.',
  notifTantangan: '🎯 Tantangan mingguan selesai! Klaim di tab Target',
  rekorJudul: '🏅 Rekor terminal',
  rekorHariIni: (p: string, rp: string) => `Hari ini: ${p} penumpang · ${rp}`,
  rekorPenumpang: 'Penumpang terbanyak sehari',
  rekorPendapatan: 'Pendapatan terbanyak sehari',
  rekorArus: 'Arus tertinggi',
  rekorBelum: '—',
  notifRekor: (p: string) => `🏅 Rekor baru: ${p} penumpang dalam sehari!`,
  // Papan peringkat mingguan (kartu tab Target & ui/peringkat.ts).
  peringkatJudul: (sisa: string) => `🏆 Papan peringkat minggu ini · berakhir dalam ${sisa}`,
  peringkatJudulPopup: '🏆 Papan peringkat',
  peringkatPenumpang: (n: string) => `Penumpangmu minggu ini: ${n}`,
  peringkatPosisi: (no: string, jumlah: string) => `Peringkatmu #${no} dari ${jumlah} terminal`,
  peringkatLuar: (batas: string, jumlah: string) => `Di luar ${batas} besar dari ${jumlah} terminal`,
  peringkatAjak: 'Adu jumlah penumpang mingguan dengan terminal pemain lain. Papan dimulai lagi tiap Senin.',
  peringkatLihat: 'Lihat papan',
  peringkatMingguIni: 'Minggu ini',
  peringkatMingguLalu: 'Minggu lalu',
  peringkatInfo: (sisa: string, jumlah: string) => `Berakhir dalam ${sisa} · ${jumlah} terminal ikut`,
  peringkatInfoLalu: (rentang: string, jumlah: string) => `Hasil akhir ${rentang} · ${jumlah} terminal`,
  peringkatNama: (nama: string) => `Terminal ${nama}`,
  peringkatLuarDaftar: (batas: string) => `${batas}+`,
  peringkatKosong: 'Belum ada terminal di papan minggu ini. Jadilah yang pertama!',
  peringkatKosongLalu: 'Tidak ada terminal di papan minggu itu.',
  peringkatMemuat: 'Memuat papan…',
  peringkatGagal: 'Papan peringkat tidak bisa dimuat. Periksa koneksi lalu coba lagi.',
  peringkatCobaLagi: 'Coba lagi',
  peringkatTamu: 'Masuk dengan Google untuk ikut. Tanpa masuk pun kamu tetap bisa melihat papan.',
  peringkatMasuk: 'Masuk untuk ikut',
  peringkatPersetujuan: 'Nama terminal, tipe terminal, dan jumlah penumpangmu minggu ini akan tampil untuk semua pemain. Nama & email akun Google tidak pernah ditampilkan. Kamu bisa keluar kapan saja.',
  peringkatIkut: 'Ikut papan peringkat',
  peringkatMengirim: 'Mengirim skor…',
  peringkatIkutTeks: 'Skormu dikirim otomatis tiap beberapa menit selama bermain. Penumpang saat game ditutup tidak dihitung.',
  peringkatKeluar: 'Keluar dari papan peringkat',
  peringkatKeluarYakin: 'Skormu akan dihapus dari papan. Kamu bisa ikut lagi kapan saja.',
  peringkatKeluarYa: 'Ya, keluar',
  peringkatKeluarGagal: 'Gagal keluar dari papan. Periksa koneksi lalu coba lagi.',
  peringkatBatal: 'Batal',
  peringkatGantiNama: 'Ganti nama',
  peringkatTutup: 'Tutup',
  // Nama terminal (ui/popup-nama.ts).
  namaTombol: 'Ubah nama terminal',
  namaJudul: 'Nama terminalmu',
  namaTeks: 'Tampil di papan gapura terminal, kartu kelas, dan foto yang kamu bagikan. Kosongkan untuk memakai nama bawaan.',
  namaContoh: 'mis. Sukamaju',
  namaPratinjau: (nama: string, kelas: string) => (nama ? `TERMINAL ${nama.toUpperCase()} · ${kelas.toUpperCase()}` : `TERMINAL ${kelas.toUpperCase()}`),
  namaSimpan: 'Simpan',
  namaBatal: 'Batal',
  notifNama: (nama: string) => `🏷️ Selamat datang di Terminal ${nama}!`,
  // Kepuasan penumpang (pil HUD & popup).
  kepuasanHud: (wajah: string, persen: number) => `${wajah} ${persen}%`,
  kepuasanTombol: 'Kepuasan penumpang',
  kepuasanJudul: (persen: number) => `Kepuasan penumpang ${persen}%`,
  kepuasanBonus: (persen: number, mulai: number, maks: number) =>
    persen > 0 ? `Bonus semua pendapatan +${persen}% (paling besar +${maks}% di kepuasan 100%)` : `Bonus pendapatan mulai di kepuasan ${mulai}%, sampai +${maks}% di 100%`,
  kepuasanPenumpang: (tambahan: number, terisi: number) =>
    `Penumpang yang datang +${tambahan}% berkat kepuasan · kapasitas terminal terisi ${terisi}% sekarang`,
  kepuasanHargaMahal: (persen: number) => `⚠ Tiket terlalu mahal: kepuasan −${persen}%. Turunkan harga di tab Jurusan & Armada.`,
  kepuasanKelancaran: 'Kelancaran antartahap',
  kepuasanFasilitas: 'Kios & Toilet',
  kepuasanJalur: 'Jalur bus',
  kepuasanSaranKelancaran: (tahap: string) => `Ada tahap yang tertinggal jauh. Upgrade ${tahap} (paling lambat).`,
  kepuasanSaranFasilitas: (ada: number, perlu: number) => `Level Kios + Toilet ${ada} dari ${perlu} yang dibutuhkan arus sekarang.`,
  kepuasanSaranJalur: (ada: number, perlu: number) => `${ada} dari ${perlu} jalur yang dibutuhkan: bus antre di jalan raya. Bangun jalur di tab Fasilitas.`,
  kepuasanBaik: 'Sudah baik.',
  kepuasanCatatan:
    'Tambahan penumpang paling terasa di luar jam sibuk; malam hari terminal tetap berangsur sepi. Terminal yang makin ramai butuh lebih banyak jalur & fasilitas. Mitra PO besar hanya mau dikontrak terminal yang penumpangnya puas.',
  kepuasanTutup: 'Tutup',
  poSyaratKepuasan: (persen: number) => `Butuh kepuasan ${persen}%`,
  // Jalur bus (tab Fasilitas).
  jalurNama: 'Jalur bus',
  jalurKeterangan: (sekarang: string, berikut: string) => `Peron & Keberangkatan ×${sekarang} · jalur berikutnya ×${berikut}. Tanpa jalur cukup, bus antre di jalan raya.`,
  jalurLengkap: (mult: string) => `Semua jalur beroperasi · Peron & Keberangkatan ×${mult}`,
  bangunJalur: (n: number) => `Bangun Jalur ${n}`,
  notifJalur: (n: number) => `🚧 Jalur ${n} dibuka! Lebih banyak bus bisa singgah sekaligus`,
  // Tab Armada: kelas bus.
  judulKelasBus: 'Kelas bus',
  judulMitraPo: 'Mitra PO',
  kelasBusRingkas: (n: number, total: number, persen: number) => `Kelas beroperasi ${n}/${total} · tiket +${persen}%`,
  kelasBusAwal: 'Beroperasi sejak awal',
  kelasBusBeroperasi: (persen: number) => `Beroperasi · tiket +${persen}%`,
  kelasBusTiket: (persen: number) => `Tiket +${persen}%`,
  kelasBusSyaratSebelumnya: (nama: string) => `Datangkan ${nama} lebih dulu`,
  kelasBusSyaratTerminal: (kelas: string) => `Butuh Terminal ${kelas}`,
  kelasBusDiulang: 'Diulang dari awal saat naik kelas terminal.',
  beli: 'Beli',
  notifKelasBus: (nama: string, persen: number) => `🚌 Armada ${nama} mulai beroperasi! Tiket +${persen}%`,
  // Tab Armada: mitra PO.
  armadaRingkas: (n: number, total: number, persen: number) => `Mitra PO ${n}/${total} · tiket +${persen}%`,
  poBergabung: (persen: number) => `Bergabung · tiket +${persen}%`,
  poSyaratJurusan: (kota: string) => `Bergabung saat jurusan ${kota} dibuka`,
  poSyaratKontrak: (persen: number) => `Kontrak sekali · tiket +${persen}% permanen`,
  kontrak: 'Kontrak',
  poIkutJurusan: (nama: string) => `${nama} ikut bergabung`,
  // Mode sinema (ui/sinema.ts).
  sinemaTombol: 'Mode sinema: rekam video timelapse',
  sinemaJudul: 'Mode sinema',
  sinemaTeks: 'Semua tampilan disembunyikan, kamera berputar pelan, dan waktu dipercepat. Rekam dengan perekam layar HP untuk TikTok atau Reels.',
  sinemaWaktu: 'Waktu',
  sinemaCuaca: 'Cuaca',
  sinemaPilihanWaktu: { cepat: '1 hari ≈ 1 menit', sedang: '1 hari ≈ 3 menit', asli: 'Asli' },
  sinemaPilihanCuaca: { jadwal: 'Sesuai jadwal', cerah: 'Cerah', hujan: 'Hujan' },
  sinemaMulai: 'Mulai',
  sinemaBatal: 'Batal',
  sinemaCatatan: 'Ketuk layar untuk keluar. Terminal tetap berjalan & menghasilkan uang seperti biasa.',
  sinemaPetunjuk: 'Ketuk layar untuk keluar',
  sinemaSitus: 'bustation.games',
  // Rute antarpulau (tab Jurusan).
  jurusanAntarpulau: '⛴ Rute antarpulau',
  lewatFeri: (feri: string) => `⛴ Menyeberang lewat ${feri}`,
  jurusanButuhTerminal: (kelas: string) => `Butuh Terminal ${kelas}`,
  notifAntarpulau: (kota: string, feri: string) => `⛴ Rute antarpulau ${kota} dibuka lewat ${feri}!`,
  notifAntarpulauPo: (kota: string, po: string) => `⛴ Rute antarpulau ${kota} dibuka! ${po} ikut bergabung`,
  poSyaratKelas: (kelas: string) => `Hadiah naik ke ${kelas}`,
  poSyaratEvent: (event: string) => `Hadiah akhir event ${event}`,
  // Event musiman (kartu di tab Target).
  eventJudul: (nama: string, tahun: string) => `${nama}${tahun ? ` ${tahun}` : ''}`,
  eventSisa: (waktu: string) => `berakhir dalam ${waktu}`,
  eventBerakhir: 'sudah berakhir',
  eventTugas: (target: string, tahap: number, jumlah: number) => `Berangkatkan ${target} penumpang (tahap ${tahap}/${jumlah})`,
  eventTuntas: 'Semua tahap selesai. Sampai jumpa di event berikutnya!',
  eventKeterangan: (pengali: string, po: string, poSudah: boolean) => `Pendapatan ×${pengali} selama event · ${poSudah ? `${po} sudah bergabung` : `hadiah akhir: ${po}`}`,
  hudEvent: (singkat: string, pengali: string) => `${singkat} ×${pengali}`,
  notifEventMulai: (ikon: string, nama: string, pengali: string) => `${ikon} ${nama} dimulai! Pendapatan ×${pengali}`,
  notifEventTahap: '🎁 Tahap event selesai! Klaim di tab Target',
  // Kelas terminal (naik kelas = prestige).
  kelasJudul: (kelas: string, nama = '') => (nama ? `Terminal ${nama} · ${kelas}` : `Terminal ${kelas}`),
  kelasBonus: (persen: number) => `Bonus pendapatan permanen +${persen}%`,
  kelasBerikut: (kelas: string, poin: number, persen: number) => `Naik ke ${kelas}: +${poin} poin, bonus jadi +${persen}%`,
  kelasSyarat: (kelas: string, poin: number) => `Naik ke ${kelas} butuh ${poin} poin dari pendapatan run ini`,
  kelasKemajuan: (run: string, perlu: string) => `${run} / ${perlu}`,
  naikKelas: 'Naik kelas',
  poin: (n: number) => `+${n} poin`,
  poinDari: (n: number, min: number) => `${n}/${min} poin`,
  kelasPopupJudul: (kelas: string) => `Naik ke ${kelas}?`,
  kelasPopupTeks: (kelas: string) => `Terminal dibangun ulang dari awal sebagai Terminal ${kelas}, dengan bonus pendapatan yang lebih besar.`,
  kelasPopupBonus: (sekarang: number, setelah: number) => `Bonus pendapatan permanen: +${sekarang}% → +${setelah}%`,
  kelasPopupReset: 'Diulang dari awal: uang, level & Kepala tiap tahap, fasilitas, jurusan, modernisasi, kelas bus.',
  kelasPopupKelasBus: (nama: string) => `Terbuka: armada ${nama}.`,
  kelasPopupTetap: 'Tetap: poin & bonus, mitra PO, penghargaan, statistik.',
  kelasPopupHadiah: (po: string) => `Hadiah: ${po} bergabung.`,
  kelasPopupNanti: 'Nanti',
  notifSiapNaikKelas: (kelas: string) => `⭐ Terminal siap naik ke ${kelas}! Lihat tab Target.`,
  notifNaikKelas: (kelas: string) => `⭐ Selamat! Terminal naik ke ${kelas}`,
  notifPo: (nama: string) => `🚌 ${nama} bergabung!`,
  notifPoBanyak: (n: number) => `🚌 ${n} mitra PO baru bergabung!`,
  // Foto terminal.
  fotoTombol: 'Foto terminal',
  fotoJudul: 'Foto terminal',
  fotoAlt: 'Foto terminal busmu',
  fotoBagikan: 'Bagikan',
  fotoSimpan: 'Simpan gambar',
  fotoTutup: 'Tutup',
  fotoTersimpan: 'Gambar disimpan ke folder unduhan.',
  fotoGagalBagikan: 'Gagal membagikan. Coba simpan gambarnya.',
  fotoKeterangan: (kelas: string, jurusan: number, arus: string, po: number, nama = '') =>
    `${nama ? `Terminal ${nama} · ${kelas}` : `Terminal ${kelas}`} · ${jurusan} jurusan · ${arus} pnp/dtk${po > 0 ? ` · ${po} PO` : ''}`,
  fotoAjakan: 'Main gratis di bustation.games',
  fotoTeksBagikan: 'Lihat terminal busku di Bustation! Main gratis di https://bustation.games',
  /** Label di atas bus yang diketuk (klakson telolet). */
  telolet: 'TELOLET!',
  tutorialSelesaiJudul: 'Terminalmu sudah berjalan!',
  tutorialSelesai:
    'Jaga kepuasan penumpang supaya terminal makin ramai, buka jurusan baru, dan kembali besok untuk target harian. Tips: ketuk bus untuk membunyikan klakson telolet!',
  offlineJudul: 'Selama kamu pergi…',
  offlineDurasi: (durasi: string, dibatasi: boolean) =>
    dibatasi ? `Terminal beroperasi ${durasi} (batas maksimal)` : `Terminal beroperasi ${durasi}`,
  offlineCatatan: (persen: number, batas: string) => `Pendapatan offline ${persen}% · maksimal ${batas}`,
  offlineButuhKepala: 'Rekrut Kepala di ketiga tahap supaya terminal tetap jalan saat kamu pergi.',
  offlineAmbil: 'Ambil',
  kecepatan: (k: number) => `Kecepatan waktu ${k}× (tombol ${k})`,
  tabTahap: 'Tahap',
  tabFasilitas: 'Fasilitas',
  tabJurusan: 'Jurusan',
  tabArmada: 'Armada',
  tabModern: 'Modern',
  tabTarget: 'Target',
  bangun: 'Bangun',
  buka: 'Buka',
  pasang: 'Pasang',
  tiketSetelahBuka: (mult: string) => `Tiket ×${mult} setelah dibuka`,
  terpasang: '✓ Terpasang',
  diklaim: '✓ Diklaim',
  klaim: 'Klaim',
  butuh: (nama: string) => `Butuh: ${nama}`,
  perPenumpang: (nilai: string) => `+Rp ${nilai}/pnp`,
  perBus: (nilai: string) => `Rp ${nilai}/bus`,
  tambahPerBus: (nilai: string) => `+Rp ${nilai}/bus`,
  sewaKios: (perHari: string, hariIni: string) => `Sewa ±${perHari}/hari · terkumpul ${hariIni}`,
  tambahBelanja: (nilai: string) => `+Rp ${nilai}/pnp`,
  bonusBelanjaKios: (persen: number) => `Belanja kios +${persen}%`,
  notifSewaKios: (hari: string, uang: string) => `🏪 Sewa kios hari ${hari}: +${uang}`,
  kapasitasPersen: (persen: number, tahap: string) => `+${persen}% kapasitas ${tahap}`,
  nilaiTiket: (mult: string, normal: string, dibayar: string) => `Tiket ×${mult} · normal Rp ${normal} · rata-rata dibayar Rp ${dibayar} per penumpang`,
  // Harga tiket per jurusan & kelas bus (tab Jurusan & Armada).
  hargaJudulJurusan: 'Harga tiket per jurusan',
  hargaCatatan:
    'Tiket = harga jurusan + tambahan kelas (tab Armada). Harga naik: tiket lebih mahal tapi peminat turun. Kursi penuh dan masih ada yang tak terangkut? Naikkan. Banyak kursi kosong? Turunkan. Ketuk saran untuk hasil terbaik sehari.',
  hargaBatasWajar: (rp: string) =>
    `Penumpang menerima tiket sampai ±Rp ${rp}. Lebih mahal dari itu mereka kecewa: kepuasan turun, peminat di semua jurusan ikut turun, bonus kepuasan hilang.`,
  hargaPenaltiAktif: (persen: number) => `⚠ Tiket terlalu mahal, penumpang kecewa: kepuasan −${persen}%. Turunkan harga yang bertanda merah.`,
  hargaSaran: (rp: string) => `Saran ${rp} (ketuk untuk pakai)`,
  hargaSesuaiSaran: '✓ Sesuai saran',
  hargaTerlaluMahal: (rp: string) => `⚠ Terlalu mahal, penumpang kecewa · saran ${rp}`,
  hargaKelasCatatan: 'Tambahan harga tiap kelas diatur dengan −/+ (tiket = harga jurusan + tambahan kelas); penumpang ekonomi paling peka harga.',
  hargaPeminat: (persen: number) => (persen === 0 ? 'Peminat normal' : `Peminat ${persen > 0 ? '+' : '−'}${Math.abs(persen)}%`),
  hargaTerisi: (persen: number) => `kursi terisi ${persen}%`,
  hargaPenuh: (lebih: number) => `kursi penuh, ${lebih}% tak terangkut`,
  hargaTurun: (nama: string) => `Turunkan harga tiket ${nama}`,
  hargaNaik: (nama: string) => `Naikkan harga tiket ${nama}`,
  bukaJurusan: (nama: string, persen: number) => `Buka ${nama} · tiket +${persen}%`,
  semuaJurusanBuka: 'Semua jurusan sudah dibuka',
  targetUpgrade: (n: string) => `Lakukan ${n} upgrade tahap`,
  targetPenumpang: (n: string) => `Berangkatkan ${n} penumpang`,
  targetHari: (hari: string) => `Target hari ${hari}`,
  penghargaan: 'Penghargaan',
  notifPencapaian: (nama: string) => `🏆 Penghargaan baru: ${nama}`,
  notifTarget: '🎯 Target harian selesai! Klaim di tab Target',
  panelRingkas: 'Ringkas',
  chipTahap: (nama: string, level: number, kapasitas: string, adaKepala: boolean) =>
    `${nama} · Lv ${level} · ${kapasitas} pnp/dtk${adaKepala ? ' · ada Kepala' : ''} (ketuk untuk buka panel)`,
  panelBuka: 'Buka panel',
  putarKiri: 'Putar kiri (Q)',
  putarKanan: 'Putar kanan (E)',
  arahAwal: 'Kompas: ketuk untuk kembali ke arah awal',
  suaraNyala: 'Suara nyala (ketuk untuk mematikan)',
  suaraMati: 'Suara mati (ketuk untuk menyalakan)',
  grafisGagal: 'Grafis 3D tidak didukung di perangkat ini. Game tetap berjalan.',
  pembaruanJudul: 'Versi baru tersedia',
  pembaruanJudulWajib: 'Pembaruan diperlukan',
  pembaruanYangBaru: 'Yang baru:',
  pembaruanCatatan: 'Progres kamu disimpan dulu, lalu game dimuat ulang beberapa detik.',
  pembaruanCatatanWajib: 'Versi ini sudah tidak didukung. Progres kamu disimpan dulu, lalu game dimuat ulang.',
  pembaruanPerbarui: 'Perbarui sekarang',
  pembaruanMemperbarui: 'Memperbarui…',
  pembaruanNanti: 'Nanti',
  pembaruanTombol: 'Versi baru tersedia: ketuk untuk memperbarui',
  akunTombol: 'Akun & simpan di cloud',
  akunJudulTamu: 'Simpan progres di cloud',
  akunPenjelasanTamu: 'Masuk dengan Google supaya progres aman dan bisa dilanjutkan di perangkat lain.',
  akunMasuk: 'Masuk dengan Google',
  akunMasukLagi: 'Masuk lagi',
  akunMemuat: 'Memuat…',
  akunMemproses: 'Memproses…',
  akunJudul: 'Akun',
  akunTersinkron: 'Progres tersimpan di cloud.',
  akunMenyinkronkan: 'Menyimpan ke cloud…',
  akunBelumTersinkron: 'Sebagian progres belum tersimpan di cloud. Dicoba lagi otomatis saat ada internet.',
  akunSesiBerakhir: 'Sesi login berakhir. Masuk lagi supaya progres kembali tersimpan di cloud.',
  akunKeluar: 'Keluar',
  akunHapus: 'Hapus akun',
  akunPrivasi: 'Kebijakan Privasi',
  akunSetujuPrivasi: 'Dengan masuk, kamu menyetujui ',
  akunTutup: 'Tutup',
  akunBatal: 'Batal',
  akunJudulKeluar: 'Keluar dari akun?',
  akunTeksKeluar: 'Progres tetap tersimpan di akun. Di perangkat ini kamu mulai sebagai tamu baru sampai masuk lagi.',
  akunYaKeluar: 'Ya, keluar',
  akunJudulHapus: 'Hapus akun?',
  akunTeksHapus: 'Progres di cloud dan di perangkat ini dihapus permanen, lalu kamu mulai dari awal. Untuk konfirmasi, pilih akun Google-mu sekali lagi.',
  akunYaHapus: 'Hapus permanen',
  akunGagalMuat: 'Layanan akun tidak bisa dimuat. Periksa koneksi internet lalu coba lagi.',
  akunGagalMasuk: 'Gagal masuk. Periksa koneksi internet lalu coba lagi.',
  akunPopupDiblokir: 'Jendela login diblokir browser. Izinkan pop-up untuk situs ini lalu coba lagi.',
  akunGagalKeluar: 'Gagal keluar. Coba lagi.',
  akunGagalHapus: 'Gagal menghapus akun. Periksa koneksi internet lalu coba lagi.',
  akunMuatUlang: 'Game dimuat ulang…',
  pilihSaveJudul: 'Pilih progres',
  pilihSaveTeksMasuk: 'Perangkat ini dan akun Google-mu punya progres berbeda. Mau lanjut yang mana?',
  pilihSaveTeksSinkron: 'Akun ini dimainkan di perangkat lain, sementara progres di sini belum tersimpan ke cloud. Mau lanjut yang mana?',
  pilihSaveLokal: 'Perangkat ini',
  pilihSaveAkun: 'Akun Google',
  pilihSaveLain: 'Perangkat lain',
  pilihSavePendapatan: (uang: string) => `Total pendapatan ${uang}`,
  pilihSaveLevel: (level: string) => `Total level ${level}`,
  pilihSavePrestige: (jumlah: string) => `Prestige ${jumlah}×`,
  pilihSaveTerakhir: (durasi: string) => `Terakhir main ${durasi} lalu`,
  pilihSaveBaruSaja: 'Terakhir main barusan',
  pilihSavePakai: 'Lanjutkan ini',
  pilihSaveCatatan: 'Progres yang tidak dipilih akan diganti.',
  notifSaveDiganti: 'Progres dari perangkat lain dimuat',
  iklanContohLabel: 'IKLAN CONTOH',
  iklanContohIsi: 'Di sini nanti iklan sungguhan diputar. Tunggu sampai selesai untuk mendapat hadiah.',
  iklanTunggu: (detik: number) => `Hadiah dalam ${detik} dtk…`,
  iklanAmbil: 'Ambil hadiah',
  iklanLewati: 'Lewati (tanpa hadiah)',
  iklanTanpaHadiah: 'Iklan dilewati, jadi tidak ada hadiah. Coba lagi kapan saja.',
  iklanGagal: 'Iklan belum tersedia. Coba lagi nanti.',
  hadiahNanti: 'Nanti',
  klaimGanda: '2×',
  offlineAmbilGanda: (uang: string) => `Ambil 2× · ${uang}`,
  offlineBoost: (durasi: string) => `Termasuk boost 2× selama ${durasi}`,
  boostHud: ' ⚡2×',
  boostTombol: 'Boost pendapatan 2× (tonton iklan)',
  boostTombolAktif: (sisa: string) => `Boost pendapatan 2× aktif, sisa ${sisa}`,
  boostJudul: 'Boost Pendapatan',
  boostTeks: (menit: number, jamMaks: number) => `Pendapatan 2× selama ${menit} menit waktu main. Bisa ditumpuk sampai ${jamMaks} jam, dan tetap berjalan saat game ditutup.`,
  boostHadiah: (menit: number) => `+${menit} menit`,
  boostSisa: (durasi: string) => `Boost aktif, sisa ${durasi}`,
  boostTonton: 'Tonton iklan',
  boostPenuh: (jam: number) => `Boost sudah penuh (${jam} jam)`,
  notifBoost: (durasi: string) => `⚡ Boost 2× aktif · sisa ${durasi}`,
  busEmasPenanda: 'Bus Emas!',
  busEmasJudul: 'Bus Emas tiba!',
  busEmasTeks: (menit: number) => `Bus istimewa membawa rombongan penumpang. Tonton iklan untuk bonus sebesar ${menit} menit pendapatan.`,
  busEmasTonton: 'Tonton iklan & ambil',
  notifBusEmas: (uang: string) => `🚌 Bus Emas: +${uang}`,
} as const;
